# permissions for end users to view cheekdeployupdates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cheekdeployupdate-viewer-role
rules:
- apiGroups:
  - aloys.cheekdeployupdate.tech
  resources:
  - cheekdeployupdates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aloys.cheekdeployupdate.tech
  resources:
  - cheekdeployupdates/status
  verbs:
  - get
