bases:
  - ../default

patches:
  - patch: |
      - op: "remove"
        path: "/spec/dnsNames"
    target:
      kind: Certificate
  - patch: |
      - op: "add"
        path: "/spec/ipAddresses"
        # value 设置的ip本机地址，要保证k8s能连接到
        value: ["172.20.10.2"]
    target:
      kind: Certificate
  - patch: |
      - op: "add"
      #  apiVersion: aloys.cheekdeployupdate.tech/v1beta1
        #kind: CheekDeployUpdate
      #  kind类型中有大写字母要变成小写的
        path: "/webhooks/0/clientConfig/url"
        value: "https://172.20.10.2:9443/mutate-aloys-cheekdeployupdate-tech-v1beta1-cheekdeployupdate"
    target:
      kind: MutatingWebhookConfiguration
  - patch: |
      - op: "add"
        path: "/webhooks/0/clientConfig/url"
        value: "https://172.20.10.2:9443/validate-aloys-cheekdeployupdate-tech-v1beta1-cheekdeployupdate"
    target:
      kind: ValidatingWebhookConfiguration
  - patch: |
      - op: "remove"
        path: "/webhooks/0/clientConfig/service"
    target:
      kind: MutatingWebhookConfiguration
  - patch: |
      - op: "remove"
        path: "/webhooks/0/clientConfig/service"
    target:
      kind: ValidatingWebhookConfiguration